version: "3.7"
services:
 app:
  build:
    args:
      user: max
      uid: 1000
    context: ./
    dockerfile: Dockerfile
  image: app
  container_name: app-main
  restart: unless-stopped
  working_dir: /var/www/
  volumes:
    - ./:/var/www
  networks:
    - first-app

 db:
  image: mysql:5.7
  container_name: app-db
  restart: unless-stopped
  environment:
    MYSQL_DATABASE: ${DB_DATABASE}
    MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    MYSQL_PASSWORD: ${DB_PASSWORD}
    MYSQL_USER: ${DB_USERNAME}
    SERVICE_TAGS: dev
    SERVICE_NAME: mysql
  volumes:
    - ./docker-compose/mysql:/docker-entrypoint-initdb.d
  networks:
    - first-app

 nginx:
  image: nginx:1.17-alpine
  container_name: app-nginx
  restart: unless-stopped
  ports:
    - 8000:80
  volumes:
    - ./:/var/www
    - ./docker-compose/nginx:/etc/nginx/conf.d
  networks:
    - first-app

networks:
 first-app:
  driver: bridge
